### ISSUE TITLE
Installed, but a couple of issues

### ISSUE THREAD

**Issue by simplelifelfk** [stormchasertech/obwx#2]
I got the skin installed, and I have it running.  But there are a couple of issues I would love to figure out how to fix:

1.  Not all of the information shows up on the webpage:  It's missing some info.
2. The connection to the MQTT server doesn't appear to have the ability to use a userid/password.  Am I missing something in the config?
Would love to help with testing.  rich@minear.org

https://www.2whippets.org/weather/obwx

<img width="1595" alt="Screenshot 2023-03-05 at 11 00 37 PM" src="https://user-images.githubusercontent.com/111659886/223023077-460af506-51f0-4c2f-9109-5c8246e50e4c.png">
<img width="863" alt="Screenshot 2023-03-05 at 11 01 29 PM" src="https://user-images.githubusercontent.com/111659886/223023477-b3ec1ed9-168b-4972-9a5f-a4ddb95334b2.png">

**Comment by stormchasertech** [comment]
The "---" fields are waiting for live updates from your sensors via a mqtt/websocket broker. Once that data is received it should update with that data.

With your webpage open, check your web browser's console which should have some information on your mqtt/websocket connection status (make sure to view 'warning' messages).

![Capture](https://user-images.githubusercontent.com/116417003/223160957-4d3c8bea-9c4b-4500-8075-96bce4bd036b.PNG)

If you are not successfully connecting please read on:

Please verify that you have the following running:
1) mqtt broker is installed, I use the [mosquitto broker](https://mosquitto.org/).
2) The broker is configured for encryption, and the correct ports are exposed in your firewall.
3) mqtt weewx extension installed, I use this [MQTT extension](https://github.com/matthewwall/weewx-mqtt).

If using the mosquitto service, you can test if it is sending data using the following terminal command (change localhost and ports as needed for your setup):
` mosquitto_sub -h localhost -p 1883 -t weather/#`

Then verify these settings are similar in weewx.conf :
    [[MQTT]]
        server_url = mqtt://USER:PASS@SERVER:PORT/
        topic = weather
        binding = loop, archive
        aggregation = aggregate

A good mqtt setup guide can be found [here](https://obrienlabs.net/how-to-setup-your-own-mqtt-broker/)

I see from your config that some of this is probably already setup on your system, but just wanted to be thorough.

**Comment by stormchasertech** [comment]
Digging a little deeper, I notice that your web-socket host is not showing correctly:

Please change your obwx setting:
websocket_host = 
it should only be your server address, not including username password

**Comment by stormchasertech** [comment]
Thanks for trying out the obwx app! 

Sharing a couple of thoughts:

I have not used a username/password for receiving/subscribing to mqtt/websocket data, including my install of Belchertown. Be advised that information is included in your online javascript file which anyone can see. 

Passwords to receive websocket data are currently not used in OBWX. If adding that option is something folks want, let me know below and I'll consider adding it, albeit a bit more securely.

To illustrate. I've attached a screenshot from your belchertown page. I've blurred out your sensitive info.

![Weewx2](https://user-images.githubusercontent.com/116417003/223199905-589bd6d3-78c0-4a0f-8f12-deb276d01ef6.PNG)


I'm not an expert on websocket/mqtt so if someone else can provide better insights, I'd be interested in hearing more.

**Comment by simplelifelfk** [comment]
Yeah....I started out with an anonymous instance of mosquito, and then some of the comments in the google support pages for belchertown/mqtt scared me a bit.  But right now...the ONLY thing I'm using it for is my Tempest weather info.  So I can change it back to anonymous.  I'm sure I can do other things with it if I choose to use it for something else also.  I will take a look tonight.

**Comment by simplelifelfk** [comment]
I got it working when I got home.  As soon as I set mosquito to anonymous, it started working!

https://www.2whippets.org/weather/obwx/

One last question:  The tab title still shows "Stormchaser.tech Weather".  Is there a place I should overwrite that?

Thanks!

**Comment by stormchasertech** [comment]
I've pushed a couple of updates:

1) Added an option to change the html window title text. I'm sure there a couple more examples of this to deal with.
 - html_title = 'your title goes here'

2) Added an option to enable username/password for receiving websocket data. Its a quick fix and certainly not a permanent solution, but at least it gives the option. Username and password will need to be entered for every page reload. I've not tested it, so please report any bugs.
 - websocketHasPassword = true/false

Thank you for reporting those issues! Also thanks for sharing your site. It is nice seeing another platform/hardware being used and I've already seen some things that need fixing.

**Comment by simplelifelfk** [comment]
I pulled an updated copy and installed it.  

it doesn't seem to matter if I put the title in " " or ' '.  It still puts "Stormchaser.tech Weather".

 [[OBWX]]
        skin = obwx
        HTML_ROOT = /var/www/html/weather/obwx
        enable = true
        [[[Extras]]]
            logo_img = https://www.2whippets.org/logo/2Whippets_Logo_2_dark.JPG
            logo_title = 2Whippets Weather
            logo_alt = 2Whippets Weather
            api_id = XXXXXXXXXXXXXXXXXXX
            api_secret = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            api_call_frequency = 240
            websocket_enable = 1
            websocket_host = mqtt.2whippets.org
            websocket_port = 443
            websocket_topic = "weather/#"
            metar_id_1 = KLWC
            metar_id_2 = KTOP
            timezone = US/Chicago
            html_title = '2Whippets Weather'

**Comment by stormchasertech** [comment]
It appears the reinstall wasn't successful, the html and js edits are not present on your site. Try uninstalling the skin before reinstalling, then restart weewx to apply config changes.

You can do a quick look at the index.html.tmpl file and should see this on line number 6 -- <title>$Extras.html_title</title>.
Also the config [[[Extras]]] section should have html_title just above the logo_img setting.
If you see both of those, your update was successful.

I did the uninstall / reinstall before the push and was successful with a reinstall, so it _should_ work.

**Comment by simplelifelfk** [comment]
Good morning.  I installed .31 this morning, and the html_title worked just like it was supposed to!  I also changed my timezone to match your doc:  America/Chicago.  All good.  

Everything seems to be working well.  Great job.

One notice:  When you first load the page, the temperature takes a bit to populate.  I'm *assuming* this is because it is waiting for a temp change to show up in the feed from MQTT.  The wind happens very quickly...but temp takes a bit.  

It's not an issue if you are putting up for a display.  But if someone uses the web to just check...they may wonder why it is taking so long...and give up.  

Looking forward to testing new stuff as you put it out!

**Comment by stormchasertech** [comment]
Happy to hear all is working as expected! 

Your assumption is correct, the live data starts empty and is populated as updates arrive. That was my preferred way when it was just me using it as a display in the kitchen. The eventual plan is to initialize the page with archive data ... it is just further down the todo list.

Thanks again! I'm marking this issue closed.
